# Generated by Django 6.1.1 on 2026-09-15 16:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(default='Koli Coastal Seafood', max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('locality', models.CharField(help_text='e.g. Satpati, Kelva, Arnala, Shirgaon, Vasai, Dahanu', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, default=19.6936, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=72.7655, max_digits=9)),
                ('price_range', models.CharField(choices=[('₹', 'Budget (Under ₹300 per person)'), ('₹₹', 'Moderate (₹300 - ₹700 per person)'), ('₹₹₹', 'Premium (₹700 - ₹1500 per person)'), ('₹₹₹₹', 'Luxury Coastal Feast (₹1500+ per person)')], default='₹₹', max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('opening_time', models.TimeField(default='11:00:00')),
                ('closing_time', models.TimeField(default='23:00:00')),
                ('average_rating', models.FloatField(default=4.5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('hero_image', models.CharField(blank=True, default='/static/images/hero-coastal.jpg', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Seafood', 'Fresh Catch & Seafood'), ('Fish', 'Fish Special (Surmai, Pomfret, Rawas)'), ('Prawns', 'Prawns (Kolambi)'), ('Crab', 'Crab (Kekda)'), ('Koli Special', 'Traditional Koli Authentic'), ('Malvani', 'Malvani Curries & Sukka'), ('Rice', 'Bhakri, Vade & Rice Preparations'), ('Thali', 'Authentic Coastal Thalis'), ('Vegetarian', 'Coastal Vegetarian & Dal'), ('Drinks', 'Solkadhi & Coastal Coolers'), ('Desserts', 'Modak & Coastal Sweets')], default='Seafood', max_length=50)),
                ('image', models.CharField(blank=True, default='/static/images/dish-fish.jpg', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reservations.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEANING', 'Cleaning')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['table_number'],
                'unique_together': {('restaurant', 'table_number')},
            },
        ),
    ]
