# Generated by Django 6.1.1 on 2026-09-15 18:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('role_in_business', models.CharField(help_text='e.g. Owner, Managing Partner, General Manager', max_length=100)),
                ('verification_notes', models.TextField(help_text='Provide business registration details, FSSAI number, GSTIN, or electric bill reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Palghar', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='claim_status',
            field=models.CharField(choices=[('UNCLAIMED', 'Unclaimed Public Listing'), ('PENDING', 'Claim Pending Verification'), ('VERIFIED', 'Verified Owner Registered'), ('REJECTED', 'Claim Rejected')], default='UNCLAIMED', max_length=25),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(default='Palghar', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='external_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='external_rating_source',
            field=models.CharField(blank=True, default='Public Reviews', max_length=80),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='True only for designated test/demo restaurants'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='True if business existence is verified from public sources'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='source_name',
            field=models.CharField(blank=True, default='Public Coastal Directory', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='source_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waqt_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waqt_status',
            field=models.CharField(choices=[('LIVE', 'Live on Waqt (Floor & Queue Connected)'), ('LISTED', 'Listed in Directory (Not Connected)'), ('DEMO', 'Waqt Pilot Demo Data')], default='LISTED', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_rating',
            field=models.FloatField(default=4.2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='locality',
            field=models.CharField(help_text='e.g. Virar, Nalasopara, Vasai, Palghar, Boisar, Tarapur, Kelva, Dahanu', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['locality'], name='restaurants_localit_24281a_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['waqt_status'], name='restaurants_waqt_st_4475ed_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['cuisine_type'], name='restaurants_cuisine_01615e_idx'),
        ),
        migrations.AddField(
            model_name='restaurantclaim',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantclaim',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='restaurants.restaurant'),
        ),
    ]
