# Generated by Django 6.1.1 on 2026-09-15 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('occupied_at', models.DateTimeField()),
                ('freed_at', models.DateTimeField()),
                ('duration_minutes', models.FloatField(help_text='Actual turnover duration in minutes')),
            ],
            options={
                'ordering': ['-freed_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('position', models.PositiveIntegerField(default=1)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting in Queue'), ('CALLED', 'Table Ready / Called'), ('SEATED', 'Seated at Table'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer'), ('EXPIRED', 'Expired / No Show')], default='WAITING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
