# Generated by Django 6.1.1 on 2026-09-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_system', '0001_initial'),
        ('reservations', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='tableturnover',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnovers', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='tableturnover',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='tableturnover',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='restaurants.restauranttable'),
        ),
    ]
