# Generated by Django 6.1.1 on 2026-09-15 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
