# Generated by Django 6.1.1 on 2026-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0003_alter_queueentry_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='actual_wait_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated upon being seated', null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting in Queue'), ('CALLED', 'Table Ready / Called'), ('SEATED', 'Seated at Table'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer'), ('EXPIRED', 'Expired'), ('NO_SHOW', 'No Show')], default='WAITING', max_length=20),
        ),
    ]
